"""
export_unified_viewer.py
=======================
Emit viewer/data_unified.js for the heat + scalar-wave viewer. The operator L is
vertex-based (cotangent/FE = heat-conductance network), so the data is the graph:
vertices, edges, per-edge conductance c_ij = -K_ij, and lumped masses M_i.

window.KSF_UNIFIED = {
  nV, verts[nV*3],
  edges[nE*2], cond[nE],     # c_ij > 0 conductances
  mass[nV],                  # lumped M_i
  kdiag[nV]                  # sum_j c_ij (for stable dt in JS)
}
The viewer integrates  heat: ṗ=-M^{-1}Kp   and  wave: p̈=-M^{-1}Kp  in JS.
"""
from __future__ import annotations
import os, sys, json
import numpy as np
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from ksf3d.mesh3d_uniform import kuhn_cube
from ksf3d.fem3d import fem_laplacian


def build(n=8):
    V, T = kuhn_cube(n)
    V = V - 0.5
    K, Mv = fem_laplacian(V, T)
    Kc = K.tocoo()
    edges, cond = [], []
    for i, j, v in zip(Kc.row, Kc.col, Kc.data):
        if i < j and abs(v) > 1e-12:
            edges.append((int(i), int(j)))
            cond.append(-float(v))      # conductance
    kdiag = np.zeros(len(V))
    for (i, j), c in zip(edges, cond):
        kdiag[i] += c; kdiag[j] += c
    return {
        "nV": int(len(V)),
        "verts": [round(float(x), 5) for x in V.flatten()],
        "edges": [int(x) for e in edges for x in e],
        "cond": [round(float(c), 6) for c in cond],
        "mass": [round(float(m), 7) for m in Mv],
        "kdiag": [round(float(k), 6) for k in kdiag],
    }


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "..", "viewer", "data_unified.js")
    d = build(n=8)
    with open(out, "w") as f:
        f.write("// Auto-generated by src/verification3d/export_unified_viewer.py\n")
        f.write("// One operator L (cotangent/FE = heat conductance network):\n")
        f.write("// vertices, edges, conductances c_ij, masses M_i. Heat + wave.\n")
        f.write("window.KSF_UNIFIED = " + json.dumps(d, separators=(",", ":")) + ";\n")
    print(f"wrote {os.path.normpath(out)}")
    print(f"  nV={d['nV']}  nE={len(d['edges'])//2}  "
          f"cond>0 (negatives={sum(1 for c in d['cond'] if c < 0)})")


if __name__ == "__main__":
    main()
