"""
export_tets_viewer.py
=====================
Generate the data file the GLSL viewer loads. Mirrors how run_all.py emits
viewer/data.js: a plain script assigning a global, so the viewer works offline
over file:// with no server and no build step.

Writes  viewer/data_uniform.js  with  window.KSF_TETS = {
    verts, tets,            # the congruent Kuhn (uniform) tetra lattice, centred
    nV, nT, n,
    port_verts, port_faces  # the regular "S-parameter tetrahedron" (4 ports)
}
"""
from __future__ import annotations
import os, sys, json
import numpy as np
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from ksf3d.mesh3d_uniform import kuhn_cube
from ksf3d.fem3d import fem_laplacian  # noqa: F401  (kept for parity / future fields)


def regular_tetrahedron():
    V = np.array([[1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, 1]], float)
    return V / np.linalg.norm(V, axis=1, keepdims=True)


def build(n=3):
    V, T = kuhn_cube(n)
    V = V - 0.5                       # centre the unit cube at the origin
    pv = regular_tetrahedron() * 0.9  # the 4 ports of the S-parameter tetra
    pf = [[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]]
    return {
        "verts": [round(float(x), 6) for x in V.flatten()],
        "tets": [int(i) for i in T.flatten()],
        "nV": int(len(V)), "nT": int(len(T)), "n": int(n),
        "port_verts": [round(float(x), 6) for x in pv.flatten()],
        "port_faces": pf,
    }


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "..", "viewer", "data_uniform.js")
    data = build(n=3)
    with open(out, "w") as f:
        f.write("// Auto-generated by src/verification3d/export_tets_viewer.py\n")
        f.write("// Uniform Kuhn tetrahedra (congruent, q=0.717) + the regular\n")
        f.write("// S-parameter tetrahedron. Loaded as a plain script so the\n")
        f.write("// viewer works offline (file://). Do not edit by hand.\n")
        f.write("window.KSF_TETS = " + json.dumps(data) + ";\n")
    print(f"wrote {os.path.normpath(out)}")
    print(f"  uniform lattice: n={data['n']}  V={data['nV']}  T={data['nT']}")
    print(f"  S-parameter tetrahedron: 4 ports, 4 faces")


if __name__ == "__main__":
    main()
