"""
export_pressure_viewer.py
=========================
Precompute the verified pressure fields for viewer/viewer_pressure.html and write
viewer/data_pressure.js. Uses the SAME solver as pressure_field_verify.py, so the
presets the viewer shows are exactly the values that pass verification.

Presets (the three verified regimes):
  - hydrostatic : K p = D(rho g), p = rho g.x   (liquid; depth-linear)
  - atmosphere  : isothermal gas p = p0 exp(-g z / c^2) evaluated on the mesh
  - acoustic    : a leapfrog snapshot of M p_tt = -c^2 K p (standing wave),
                  plus the lowest eigenmode as a clean reference

Also emits mesh geometry (verts, boundary/all triangles, wireframe edges) like
the unified exporter, so the viewer renders identically (faces + slice + wire).
"""
import os, sys, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import numpy as np
from scipy.sparse import diags
from scipy.sparse.linalg import spsolve, eigsh
from ksf3d.mesh3d_uniform import kuhn_cube
from ksf3d.fem3d import fem_laplacian

FACE_COMBOS = [(0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3)]


def operators(V, T):
    tets = []
    for tet in T:
        ix = [int(i) for i in tet]
        P = V[ix]
        vol = abs(np.linalg.det(np.array([P[1]-P[0], P[2]-P[0], P[3]-P[0]]))) / 6.0
        if vol <= 1e-15:
            continue
        C = np.linalg.inv(np.column_stack([np.ones(4), P]))
        tets.append((ix, vol, C[1:4, :]))
    K, M = fem_laplacian(V, T)
    return K, M, tets


def div_source(f_tet, tets, n):
    b = np.zeros(n)
    for t, (ix, vol, G) in enumerate(tets):
        c = vol * (G.T @ f_tet[t])
        for a in range(4):
            b[ix[a]] += c[a]
    return b


def solve_neumann(K, b, pin=0):
    n = K.shape[0]
    keep = np.ones(n, bool); keep[pin] = False
    p = np.zeros(n)
    p[keep] = spsolve(K[keep][:, keep].tocsc(), b[keep])
    return p


def faces(T):
    cnt = {}
    for tet in T:
        for fc in FACE_COMBOS:
            k = tuple(sorted(int(tet[i]) for i in fc))
            cnt[k] = cnt.get(k, 0) + 1
    return ([list(k) for k, c in cnt.items() if c == 1],
            [list(k) for k in cnt.keys()])


def all_edges(T):
    es = set()
    for tet in T:
        for a in range(4):
            for b in range(a+1, 4):
                es.add(tuple(sorted((int(tet[a]), int(tet[b])))))
    return [list(e) for e in es]


def hydrostatic(V, K, tets, rho=1.0, g=(0, 0, -1.0)):
    g = np.array(g, float)
    f = np.tile(rho * g, (len(tets), 1))
    p = solve_neumann(K, div_source(f, tets, len(V)))
    return p


def atmosphere(V, p0=1.0, g=1.0, c2=0.15):
    z = V[:, 2] - V[:, 2].min()             # height from the floor
    return p0 * np.exp(-g * z / c2)


def acoustic(V, K, M, c=1.0, steps=120):
    """Standing-wave snapshot of M p_tt = -c^2 K p, seeded by the lowest mode."""
    Minv = 1.0 / M
    lam, vec = eigsh(K, k=2, M=diags(M), sigma=1e-8, which="LM")
    mode = vec[:, np.argsort(lam)[1]]
    lam_max = 2.2 * float(np.max(K.diagonal() * Minv)) * c * c
    dt = 0.4 * np.sqrt(4.0 / lam_max)
    p0 = mode.copy(); p1 = mode.copy()
    for _ in range(steps):
        p2 = 2*p1 - p0 - dt*dt*Minv*(c*c*(K @ p1))
        p0, p1 = p1, p2
    return mode, p1


def norm(p):
    a = float(np.max(np.abs(p)))
    return (p / a).tolist() if a > 0 else p.tolist()


def build(n=8):
    V, T = kuhn_cube(n); V = V - 0.5
    K, M, tets = operators(V, T)
    bnd, allf = faces(T)
    wed = all_edges(T)

    p_hydro = hydrostatic(V, K, tets, rho=1.0, g=(0, 0, -1.0))
    p_atmos = atmosphere(V, p0=1.0, g=1.0, c2=0.15)
    mode, p_acou = acoustic(V, K, M, c=1.0)

    presets = {
        "hydrostatic": {"label": "hydrostatic (liquid)  p = rho g h",
                        "signed": False, "p": norm(p_hydro)},
        "atmosphere": {"label": "atmosphere (gas)  p = p0 exp(-g z / c^2)",
                       "signed": False, "p": norm(p_atmos)},
        "acoustic": {"label": "acoustic wave  M p_tt = -c^2 K p",
                     "signed": True, "p": norm(p_acou)},
    }
    return {
        "nV": int(len(V)),
        "verts": [round(float(x), 5) for x in V.flatten()],
        "btris": [int(x) for t in bnd for x in t],
        "atris": [int(x) for t in allf for x in t],
        "wedges": [int(x) for e in wed for x in e],
        "presets": presets,
    }


def main():
    d = build(8)
    out = os.path.join(os.path.dirname(__file__), "..", "..", "viewer", "data_pressure.js")
    out = os.path.normpath(out)
    with open(out, "w") as f:
        f.write("// Auto-generated by src/verification3d/export_pressure_viewer.py\n")
        f.write("// Verified pressure fields (same solver as pressure_field_verify.py).\n")
        f.write("// Presets: hydrostatic (liquid), atmosphere (gas), acoustic (wave).\n")
        f.write("window.KSF_PRESSURE = ")
        json.dump(d, f, separators=(",", ":"))
        f.write(";\n")
    print("wrote", out)
    print(f"  nV={d['nV']}  btris={len(d['btris'])//3}  atris={len(d['atris'])//3}  "
          f"wedges={len(d['wedges'])//2}  presets={list(d['presets'])}")


if __name__ == "__main__":
    main()
